# Archivo: queries.properties
# Consultas con parámetros (?)
ver_usuarios=SELECT * FROM usuarios
buscar_usuario=SELECT * FROM usuarios WHERE id = ?
insertar_usuario=INSERT INTO usuarios (nombre) VALUES (?)
restar_saldo=UPDATE cuentas SET saldo = saldo - ? WHERE id = ?
sumar_saldo=UPDATE cuentas SET saldo = saldo + ? WHERE id = ?